
### Data Frame


```{r}
df <- data.frame(x = 1:3, y = c("a", "b", "c"))
str(df)
```

```{r}
df <- data.frame(
  x = 1:3,
  y = c("a", "b", "c"),
  stringsAsFactors = FALSE)
str(df)
attributes(df)
View(df)

as.data.frame(as.matrix(df), stringsAsFactors = F)
as.matrix(df)



```


##### subsets

```{r}
x <- c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) <- c('a', 'b', 'c', 'd', 'e')
x

x[1]
x[4]

x[1:4]

x[c(1,1,3)]

x[6]

```



#### Add one more element

```{r}

x <- c(5.4, 6.2, 7.1, 4.8, 7.5, 7.2)
names(x) <- c('a', 'b', 'c', 'd', 'e')
x

x[6]
names(x)[6] <- c("f")
x

x
x > 6
x[x >6]
x[x > mean (x)]
mean(x)


```

### Subset list

```{r}
lst <- list(1:3, "a", c(TRUE, FALSE, TRUE), c(2.3, 5.9))
names(lst) <- c("A","B","C","D")
lst

lst[1]

str(lst[1])
str(lst[[1]])

str(lst$A)
lst$A
```


#### Subsets in data frames

```{r}
df <- data.frame(
  x = 1:3,
  y = c("a", "b", "c"),
  z = c(TRUE,FALSE,TRUE),
  stringsAsFactors = FALSE)
str(df)

df$y
df[2]
str(df[2]) ### will bring an subset as data frame
df[2,3]

df[2,]
```


##### Install packages

```{r}
if (!require("tidyverse")) install.packages("tidyverse")
```

```{r}
data <- 
```




