---
title: "R lesson 4"
author: "Anderson Verzegnazzi"
date: "October 3, 2018"
output: html_document
---

```{r}

library("tidyverse")
fang <- read.delim("fang_et_al_genotypes.txt")
snp <- read.delim("snp_position.txt")
```


```{r}
library("tidyverse")
dvst <- read_csv("https://raw.githubusercontent.com/vsbuffalo/bds-files/master/chapter-08-r/Dataset_S1.txt")

dvst
View(dvst)
colnames(dvst)

colnames(dvst)[12] <- "percent.GC" #rename X.GC columns
colnames(dvst)
dvst$GC.binned <- cut(dvst$percent.GC, 5) # create a new column from existing dat

```


#### dplyr basics

```{r}

summary(dvst$`total SNPs`)

# or with dplyr
summary(select(dvst,`total SNPs`)) #this does not look simpler, but wait...

filter(dvst,`total SNPs` >= 85)
filter(dvst, Pi > 16, percent.GC > 80)

```



### exercise 

```{r}
summary(select(dvst, percent.GC))
filter(dvst, percent.GC > 85)
filter(dvst, percent.GC < 1)

filter(dvst,`total SNPs` <= 0)

filter(dvst, between(`total SNPs`, 50, 60))  
filter(dvst, between(`percent.GC`, 39, 49)) 


addcolumn <-  mutate(dvst, cent = start >= 25800000 & end <= 29700000) %>% filter(cent == TRUE)



```

```{r}
dvst %>% by_cent <- group_by(dvst, cent) %>% summarise(by_cent, GC = mean(percent.GC, na.rm = TRUE), averageSNPs=mean(`total.SNPs`, na.rm = TRUE), allSNPs=sum(`total.SNPs`))


```


